default:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: "{{ env_var('target_catalog', 'dev') }}"
      schema: cur_uki_ecommerce
      host: "{{ env_var('host') }}"
      http_path: "{{ env_var('http_path') }}"
      token: "{{ env_var('token') }}"
      auth_type: databricks_cli
      threads: 16


