default:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: "{{ var('target_catalog', 'dev') }}"
      schema: cur_uki_ecommerce
      host: "{{ var('host') }}"
      http_path: "{{ var('http_path') }}"
      token: "{{ var('token') }}"
      auth_type: databricks_cli
      threads: 16


